### ISSUE TITLE
Publish 0.22 to pipy

### ISSUE THREAD

**Issue by edgBR** [microsoft/ray-on-aml#14]
Hi,

The last version that can be installed from PyPI is 0.21, this one does not have incorporated the ray start arguments which is kind of a need if you are running ray interactively (as you will have to play with the system config to not saturate the disk space of a compute instances, which is limited to 120GBs)

Could you please publish it there?

BR
E

**Comment by Joseph-Sarsfield** [comment]
Agreed, would be useful to have this feature on pypi.

**Comment by james-tn** [comment]
Hi, thanks for the feedback. I'll look into this and will have something out soon.

**Comment by Joseph-Sarsfield** [comment]
ray init kwargs would be helpful as well

**Comment by james-tn** [comment]
What do you think about the use of just [ray client](https://docs.ray.io/en/latest/cluster/running-applications/job-submission/ray-client.html) instead of using the CI as the head node? Ray client now can run code just like you're on head node. It's easier to configure the remote cluster (e.g. avoid issue with python version mismatch).
So I will deprecate the use of CI as the direct head node in the next release.

**Comment by james-tn** [comment]
Checkout the new version. All options are there
